### ISSUE TITLE
Help syntax in checking if element exists in numpy array and then finding its index

### ISSUE THREAD

**Issue by haerynkim** [haerynkim/bme590hrm#13]
In my [read_bpm.py](https://github.com/haerynkim/bme590hrm/read_bpm.py),
I am struggling with syntax issues. What I intend to do in this function is to find the index of the user-specified start and end points and cut my time and voltage arrays to calculate the mean heartrate just within that period. Right now, I am using syntax like "numpy.where(time==starttime)[0][0]" because the numpy.where command returns a tuple. But for some files, I get this error:

Traceback (most recent call last):
  File "/Users/haerynkim/PycharmProjects/bme590hrm/read_bpm.py", line 36, in <module>
    bpm = read_bpm(t,V,0.0,15.0)
  File "/Users/haerynkim/PycharmProjects/bme590hrm/read_bpm.py", line 22, in read_bpm
    endidx = numpy.where(time==endtime)[0][0]
IndexError: index 0 is out of bounds for axis 0 with size 0

which most likely means my 'numpy.where(time==endtime)' is not returning a tuple as I anticipated. If so, how do I check if those values actually exist and ensure it will return a tuple; and what is a graceful way to handle this error if I can't fix it?

Should I give up using numpy.arrays and use lists instead? The latter seems much more reliable to use.

**Comment by dward2** [comment]
When I try to run read_bpm.py that I find on the master branch, I get errors other than the one above.   Is there a different version of the file that I should try?

**Comment by dward2** [comment]
The first error I get is an indentation error.  I will assume that I should indent the two lines between 
`if (starttime in time) == True and (endtime in time) == True:`
and
`else:`

I get a second error that I believe is due to the fact that you are sending an end time of 15, but the time array ends at 13.887.  So, I change the end time to 13.

Then, the program runs without an error.  So, I will need some guidance on how you generated your error above.
